/**
 * Datos de demostración para el Website público de TrackFlow.
 * Usa los tipos compartidos de @trackflow/logic para mantener consistencia.
 */

import type { Product, Shipment } from "@trackflow/logic";

export function getDemoProducts(): Product[] {
  return [
    {
      id: "PRD-SHOE-001",
      sku: "SHOE-NIKE-AIR",
      name: "Nike Air Max 90",
      category: "Fashion",
      weightKg: 0.4,
      dimensions: { lengthCm: 32, widthCm: 20, heightCm: 12 },
      stockQuantity: 45,
      minStockThreshold: 10,
      unitCostUSD: 120,
      isFragile: false,
      warehouse: "Los Angeles",
      status: "Active",
    },
    {
      id: "PRD-LAPTOP-001",
      sku: "LAPTOP-DELL-15",
      name: "Laptop Dell 15 pulgadas",
      category: "Electronics",
      weightKg: 2.3,
      dimensions: { lengthCm: 40, widthCm: 28, heightCm: 3 },
      stockQuantity: 8,
      minStockThreshold: 10,
      unitCostUSD: 650,
      isFragile: true,
      warehouse: "Zaragoza",
      status: "Low stock",
    },
    {
      id: "PRD-PERFUME-001",
      sku: "PERF-CHANEL-5",
      name: "Chanel No. 5 Eau de Parfum",
      category: "Cosmetics",
      weightKg: 0.25,
      dimensions: { lengthCm: 10, widthCm: 6, heightCm: 6 },
      stockQuantity: 120,
      minStockThreshold: 20,
      unitCostUSD: 85,
      isFragile: true,
      warehouse: "Los Angeles",
      status: "Active",
    },
    {
      id: "PRD-SOFA-001",
      sku: "SOFA-IKEA-KLIPP",
      name: "IKEA Klippan Sofá 2 plazas",
      category: "Home",
      weightKg: 25.0,
      dimensions: { lengthCm: 180, widthCm: 80, heightCm: 70 },
      stockQuantity: 3,
      minStockThreshold: 2,
      unitCostUSD: 350,
      isFragile: false,
      warehouse: "Zaragoza",
      status: "Low stock",
    },
    {
      id: "PRD-IPHONE-001",
      sku: "IPHONE-16-PRO",
      name: "iPhone 16 Pro 256GB",
      category: "Electronics",
      weightKg: 0.22,
      dimensions: { lengthCm: 15, widthCm: 7.5, heightCm: 0.8 },
      stockQuantity: 0,
      minStockThreshold: 15,
      unitCostUSD: 1200,
      isFragile: true,
      warehouse: "Los Angeles",
      status: "Out of stock",
    },
    {
      id: "PRD-BOOK-001",
      sku: "BOOK-TS-ADVANCED",
      name: "TypeScript Avanzado - 2da Edición",
      category: "Other",
      weightKg: 0.8,
      dimensions: { lengthCm: 24, widthCm: 17, heightCm: 3 },
      stockQuantity: 60,
      minStockThreshold: 10,
      unitCostUSD: 45,
      isFragile: false,
      warehouse: "Zaragoza",
      status: "Active",
    },
  ];
}

export function getDemoShipments(): Shipment[] {
  return [
    {
      id: "SH-2024-8821",
      sku: "LAPTOP-DELL-15",
      quantity: 1,
      origin: "Zaragoza",
      destination: { city: "Madrid", country: "Spain", postalCode: "28001", distanceKm: 320 },
      priority: "Express",
      declaredValueUSD: 650,
      carrier: "SEUR",
      status: "In transit",
      createdAt: new Date("2024-03-15"),
    },
    {
      id: "SH-2024-8822",
      sku: "SHOE-NIKE-AIR",
      quantity: 2,
      origin: "Los Angeles",
      destination: { city: "New York", country: "USA", postalCode: "10001", distanceKm: 3940 },
      priority: "Standard",
      declaredValueUSD: 240,
      carrier: "UPS",
      status: "Delivered",
      createdAt: new Date("2024-03-10"),
    },
    {
      id: "SH-2024-8823",
      sku: "PERF-CHANEL-5",
      quantity: 3,
      origin: "Los Angeles",
      destination: { city: "Miami", country: "USA", postalCode: "33101", distanceKm: 3900 },
      priority: "Express",
      declaredValueUSD: 255,
      carrier: null,
      status: "Pending",
      createdAt: new Date("2024-03-18"),
    },
  ];
}
